name: Build ARM template

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build bicep
      uses: Azure/bicep-build-action@v1.0.0
      with:
        bicepFilePath: azuredeploy.bicep
        outputFilePath: azuredeploy.json
    
    - uses: actions/upload-artifact@v3.0.0
      with:
        name: arm
        path: azuredeploy.json
        retention-days: 1
        if-no-files-found: error