name: Validate ARM template

on:
  pull_request:
    branches: [develop, production]

  workflow_dispatch:

  workflow_call:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  validate:
    name: Validate
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: arm

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate ARM template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: analogio-dev
          scope: subscription
          region: "West Europe"
          template: azuredeploy.json
          deploymentMode: Validate
          parameters: "environment=dev"
          failOnStdErr: false
