name: Deploy ARM template

on:
  push:
    branches: [develop, production, feature/shifty]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    name: Deploy ARM template
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: arm

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ARM template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: analogio-dev
          scope: subscription
          region: 'West Europe'
          template: azuredeploy.json
          parameters: "environment=dev"
          deploymentMode: Complete
          deploymentName: 'azuredeploy-${{github.run_number}}'
          failOnStdErr: false
