name: Azure deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy_dev:
    name: Deploy to dev
    needs: [ build ]
    uses: ./.github/workflows/deploy_template.yml
    secrets: inherit
    with:
      environment: dev
      subscriptionId: analogio-dev
    concurrency:
      group: dev
      cancel-in-progress: false

  deploy_prod:
    name: Deploy to prod
    needs: [ deploy_dev ]
    uses: ./.github/workflows/deploy_template.yml
    secrets: inherit
    with:
      environment: prd
      subscriptionId: analogio-prd
    concurrency:
      group: prd
      cancel-in-progress: false
