name: Deploy ARM template

on:
  push:
    branches: [main, feature/atro/dynamicAppSettings]

jobs:
  build_validate:
    name: Build and validate
    uses: ./.github/workflows/build-validate.yml
    secrets: inherit

  deploy_dev:
    name: Deploy to dev
    needs: [build_validate]
    uses: ./.github/workflows/deploy_template.yml
    secrets: inherit
    with:
      environment: dev
      subscriptionId: analogio-dev

  deploy_prod:
    name: Deploy to prod
    needs: [deploy_dev]
    uses: ./.github/workflows/deploy_template.yml
    secrets: inherit
    with:
      environment: prod
      subscriptionId: analogio-prd
