name: Validate ARM template

on:
  pull_request:
    branches: [develop, production]

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  validate:
    name: Validate ARM template
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: arm

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/arm-deploy@v1
        with:
          subscriptionId: analogio-dev
          scope: resourcegroup
          resourceGroupName: shared
          template: azuredeploy.json
          deploymentMode: Validate
          parameters: "environment=dev"
          failOnStdErr: false
